[build]
command = "npm run stackbit-build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"

[dev]
command = "npm run stackbit-dev"
targetPort = 3000

[context.production]
command = "npm run stackbit-build"

[context.deploy-preview]
command = "npm run stackbit-build"
