[build]
command = "npm run stackbit-build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"
NEXT_WEBPACK_CACHE = "true"
NEXT_USE_NETLIFY_EDGE = "true"

[dev]
command = "npm run stackbit-dev"
targetPort = 3000

[context.production]
command = "npm run stackbit-build"

[context.deploy-preview]
command = "npm run stackbit-build"

[[plugins]]
package = "@netlify/plugin-nextjs"
